services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng-core
    restart: always
    ports:
      - "8123:8080"
    networks:
      - coolify
    environment:
      - SEARXNG_VALKEY_URL=redis://:Gonzales220@84.247.137.97:6379/1
      - SEARXNG_REDIS_URL=redis://:Gonzales220@84.247.137.97:6379/1
      - SEARXNG_BASE_URL=http://84.247.137.97:8123/
      - SEARXNG_SECRET_KEY=Gonzales2026_Key_Secure

      # ESTO ES LO QUE DESBLOQUEA EL JSON DE RAÍZ:
      # Forzamos la desactivación de la seguridad de bots individualmente
      - SEARXNG_BOTDETECTION_INTERNAL_AUTH_ACTIVE=false
      - SEARXNG_SEARCH_FORMATS=html,json
      
      # Opcional para limpiar logs
      - SEARXNG_ENGINES_WIKIDATA_DISABLED=true
      - SEARXNG_ENGINES_AHMIA_DISABLED=true
      - SEARXNG_ENGINES_TORCH_DISABLED=true

networks:
  coolify:
    external: true
