services:
  searxng:
    container_name: searxng
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8123:8080"
    environment:
      # Ya no necesitamos SEARXNG_SETTINGS_PATH porque los archivos ya están donde deben estar por defecto
      - SEARXNG_VALKEY_URL=redis://:Gonzales220@84.247.137.97:6379/0
      - SEARXNG_BASE_URL=http://84.247.137.97:8123/
      - SEARXNG_SECRET_KEY=Gonzales2026_Key_Secure
    restart: always
