# settings.yml
use_default_settings: true

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "Gonzales2026_Secret_Key" # Cambia esto
  base_url: http://84.247.137.97:8123/

search:
  safe_search: 0
  autocomplete: ""

formats:
  - html
  - json

# USAR VALKEY EN LUGAR DE REDIS
valkey:
  url: redis://:Gonzales220@84.247.137.97:6379/0

engines:
  - name: google
    engine: google
  - name: bing
    engine: bing
  - name: wikidata
    disabled: true  # <--- Mata el KeyError: 'name'
  - name: ahmia
    disabled: true  # <--- Mata el error de Tor
  - name: torch
    disabled: true   # <--- Mata el error de Tor

enabled_plugins:
  - 'Hash plugin'
  - 'Self hoster'
